"""Point the parity tests at the trimmed, committed fixtures.

ida.data.load_dataset reads from data.DATA_DIR. For tests we redirect that to
tests/fixtures/ (regenerated by tests/make_fixtures.py) so the suite runs
without the full ~1.1 GB Eurostat cache. Done at import time, before any test
fixture loads data, and the load_dataset cache is cleared for safety.
"""
from pathlib import Path

from ida import data

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"
data.DATA_DIR = FIXTURES_DIR
data.load_dataset.cache_clear()
